# Generated by Django 2.2.5 on 2019-10-06 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.UUID('b720a9c5-bf77-421d-a322-445a51e168b9'), editable=False, unique=True)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('context', models.TextField(blank=True, null=True)),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserMessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
