# Generated by Django 2.2.5 on 2019-10-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_read', models.BooleanField(blank=True, db_index=True, default=False)),
                ('context', models.TextField(blank=True, null=True)),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserMessages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_read', 'user_receiver'),
            },
        ),
    ]
