# Generated by Django 2.2.5 on 2019-09-23 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='title',
        ),
        migrations.RemoveField(
            model_name='updatemessages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='updatemessages',
            name='title',
        ),
        migrations.AddField(
            model_name='messages',
            name='context',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='updatemessages',
            name='context',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_receivers',
            field=models.ManyToManyField(related_name='UserMessages', to=settings.AUTH_USER_MODEL),
        ),
    ]
