# Generated by Django 2.2.5 on 2019-09-29 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemessages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f97fdd52-414d-41ca-a50d-afb7340ccb22'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
