# Generated by Django 2.2.5 on 2019-10-06 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ba919aba-2cd2-42e3-8b6f-a92df26609f2'), editable=False, unique=True),
        ),
    ]
