# Generated by Django 2.2.6 on 2019-10-06 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('a12d7284-b7b2-456c-b6a4-8c1701394d2c'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
