# Generated by Django 2.2.5 on 2019-09-30 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0002_auto_20190929_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemessages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('15c99459-336e-4fcd-aa93-4816cd6a82ba'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
