# Generated by Django 2.2.5 on 2019-10-06 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0002_auto_20191006_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c07ae5d4-56b8-4481-bc52-8ed2ffd58d0e'), editable=False, unique=True),
        ),
    ]
