# Generated by Django 2.2.5 on 2019-10-04 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0002_auto_20190929_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemessages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('47b68755-9aab-4a07-8d3d-15466496aa27'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
