# Generated by Django 2.2.5 on 2019-10-06 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0003_auto_20191006_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('is_read', 'user_receiver')},
        ),
        migrations.AlterField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('2dd82ba7-8d1c-4e2b-b247-0fc075326380'), editable=False, unique=True),
        ),
    ]
