# Generated by Django 2.2.5 on 2019-10-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insite_messaging', '0003_auto_20191004_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemessages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b177bcd4-95de-4854-8ef7-47b7e060797d'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('0f56b006-7c5a-4e45-8b82-f285059fb339'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('context', models.TextField(blank=True, null=True)),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserMessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
