# Generated by Django 2.2.5 on 2019-10-04 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0004_auto_20191004_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d59f9bf0-721f-46b9-9c75-a77f53e43096'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='updatemessages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('a77bf1dd-a237-43ba-bc8a-d2ebd3f2771d'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
