# Generated by Django 2.2.5 on 2019-10-06 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0004_auto_20191006_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
