# Generated by Django 2.2.5 on 2019-10-04 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0007_auto_20191004_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d8ea883d-9e20-4e85-a4e2-6c0d2e3befa4'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='updatemessages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2be91d1b-521b-4dd7-8b83-5c2ea553b481'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
