# Generated by Django 2.2.5 on 2019-10-04 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0008_auto_20191004_0732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateMessages',
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('40477f10-8aa5-4f9c-a404-39e639ba22f3'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
