# Generated by Django 2.2.5 on 2019-10-06 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0009_auto_20191004_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('is_read', 'user_receiver')},
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
