# Generated by Django 2.2.4 on 2019-10-05 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0009_auto_20191004_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('12aa421a-c799-4820-82f9-2fbe15169888'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
