# Generated by Django 2.2.4 on 2019-10-05 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insite_messaging', '0010_auto_20191005_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b2a707c9-0f9d-49e4-b3e0-b6009649f28d'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
