# Generated by Django 2.2.3 on 2019-09-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hobby', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('hobby2', models.CharField(blank=True, max_length=20, null=True)),
                ('hobby3', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('hobby1', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('publication_date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Price')),
                ('authors', models.ManyToManyField(to='Publish.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publish.Publisher', verbose_name='Press')),
            ],
        ),
    ]
