# Generated by Django 2.2.1 on 2019-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hobby1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
