# Generated by Django 2.2.1 on 2019-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0002_auto_20190622_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hobby2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='hobby3',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
