# Generated by Django 2.2.5 on 2019-09-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insite_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatemessages',
            name='user_receiver',
        ),
        migrations.AddField(
            model_name='updatemessages',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
