# Generated by Django 2.2.5 on 2019-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insite_notifications', '0002_auto_20190918_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemessages',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
