# Generated by Django 2.2.1 on 2019-06-25 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('extra_field', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, max_length=128)),
                ('action_object_object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('actor_object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('target', models.CharField(db_index=True, max_length=128)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object', to='contenttypes.ContentType')),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backends', models.ManyToManyField(blank=True, help_text='Backend that specified for this subscription.', to='django_signal_notifier.Backend', verbose_name='Backend')),
                ('receiver_groups', models.ManyToManyField(blank=True, help_text='Groups that are related to this subscription.', to='auth.Group', verbose_name='Receiver_Groups')),
                ('receiver_users', models.ManyToManyField(blank=True, help_text='Users that are related to this subscription.', to=settings.AUTH_USER_MODEL, verbose_name='Receiver_Users')),
                ('trigger', models.OneToOneField(help_text='Trigger that is related to this subscription.', on_delete=django.db.models.deletion.CASCADE, to='django_signal_notifier.Trigger', verbose_name='Trigger')),
            ],
        ),
    ]
