# Generated by Django 2.2.3 on 2019-07-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_signal_notifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='action_object_object_id',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='actor_content_type',
        ),
        migrations.AddField(
            model_name='trigger',
            name='action_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='actor_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_object', to='contenttypes.ContentType'),
        ),
    ]
