# Generated by Django 2.2.5 on 2019-09-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enabled',
            field=models.BooleanField(default=True, help_text="If It isn't enabled, The subscription will be ignored"),
        ),
        migrations.AlterField(
            model_name='backend',
            name='message_template',
            field=models.CharField(choices=[('BaseMessageTemplate', 'BaseMessageTemplate'), ('SimpleEmailMessageTemplate', 'SimpleEmailMessageTemplate'), ('SimpleTelegramMessageTemplate1', 'SimpleTelegramMessageTemplate1'), ('SimpleTelegramMessageTemplate2', 'SimpleTelegramMessageTemplate2'), ('NewMessageTemplate', 'NewMessageTemplate')], default='BaseMessageTemplate', max_length=128),
        ),
        migrations.AlterField(
            model_name='backend',
            name='messenger',
            field=models.CharField(choices=[('SimplePrintMessenger', 'SimplePrintMessenger'), ('SimplePrintMessengerTemplateBased', 'SimplePrintMessengerTemplateBased'), ('SMTPEmailMessenger', 'SMTPEmailMessenger'), ('TelegramBotMessenger', 'TelegramBotMessenger'), ('NewMessenger', 'NewMessenger')], default='BaseMessanger', max_length=128),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trigger',
            field=models.ForeignKey(help_text='A Trigger that is related to this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='django_signal_notifier.Trigger'),
        ),
    ]
