# Generated by Django 2.2.1 on 2019-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='name',
            field=models.CharField(default='BaseMessanger', max_length=128, unique=True),
        ),
    ]
