# Generated by Django 2.2.7 on 2019-12-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='messenger',
            field=models.CharField(choices=[('SimplePrintMessenger', 'SimplePrintMessenger'), ('AnotherSimplePrintMessenger', 'AnotherSimplePrintMessenger'), ('SimplePrintMessengerTemplateBased', 'SimplePrintMessengerTemplateBased'), ('SMTPEmailMessenger', 'SMTPEmailMessenger'), ('TelegramBotMessenger', 'TelegramBotMessenger'), ('NewMessenger', 'NewMessenger'), ('InsitMessagingMessenger', 'InsitMessagingMessenger')], default='BaseMessanger', max_length=128),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='action_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object', to='contenttypes.ContentType'),
        ),
    ]
