# Generated by Django 2.2.3 on 2019-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(choices=[('SimplePrintMessenger1', 'SimplePrintMessenger1'), ('EmailMessenger', 'EmailMessenger')], default='BaseMessanger', max_length=128, unique=True),
        ),
    ]
