# Generated by Django 2.2.1 on 2019-06-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0002_backend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(choices=[('SimplePrintMessagner1', 'SimplePrintMessagner1'), ('SimplePrintMessagner2', 'SimplePrintMessagner2')], default='BaseMessanger', max_length=128, unique=True),
        ),
    ]
