# Generated by Django 2.2.3 on 2019-07-27 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0002_auto_20190727_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='receiver_users',
            field=models.ManyToManyField(blank=True, help_text='Users that are related to this subscription.', related_name='nyt_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Receiver_Users'),
        ),
    ]
