# Generated by Django 2.2.5 on 2019-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0002_auto_20190930_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='enabled',
            field=models.BooleanField(default=True, help_text="If It's disabled, Subscription will be ignored"),
        ),
    ]
