# Generated by Django 2.2.3 on 2019-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0003_auto_20190727_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(choices=[('SimplePrintMessenger1', 'SimplePrintMessenger1'), ('SMTPEmailMessenger', 'SMTPEmailMessenger')], default='BaseMessanger', max_length=128, unique=True),
        ),
    ]
