# Generated by Django 3.0.3 on 2020-03-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0003_auto_20200204_1205'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.UniqueConstraint(fields=('verb', 'action_object_content_type', 'action_object_id', 'actor_object_content_type', 'actor_object_id', 'target'), name='Trigger_Unique_Index'),
        ),
    ]
