# Generated by Django 2.2.5 on 2019-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0004_auto_20191004_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='messenger',
            field=models.CharField(choices=[('SimplePrintMessenger', 'SimplePrintMessenger'), ('SimplePrintMessengerTemplateBased', 'SimplePrintMessengerTemplateBased'), ('SMTPEmailMessenger', 'SMTPEmailMessenger'), ('TelegramBotMessenger', 'TelegramBotMessenger'), ('NewMessenger', 'NewMessenger'), ('InsitMessagingMessenger', 'InsitMessagingMessenger')], default='BaseMessanger', max_length=128),
        ),
    ]
