# Generated by Django 3.1.7 on 2021-03-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0004_auto_20200309_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='message_template',
            field=models.CharField(choices=[('BaseMessageTemplate', 'BaseMessageTemplate'), ('SimplePrintMessageTemplate', 'SimplePrintMessageTemplate'), ('SimpleTelegramMessageTemplate1', 'SimpleTelegramMessageTemplate1'), ('SimpleTelegramMessageTemplate2', 'SimpleTelegramMessageTemplate2'), ('SimpleSMTPMessageTemplate', 'SimpleSMTPMessageTemplate'), ('NewMessageTemplate', 'NewMessageTemplate')], default='BaseMessageTemplate', max_length=128),
        ),
    ]
