# Generated by Django 2.2.3 on 2019-07-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0004_basicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='receiver_users',
            field=models.ManyToManyField(blank=True, help_text='Users that are related to this subscription.', to='django_signal_notifier.BasicUser', verbose_name='Receiver_Users'),
        ),
    ]
