# Generated by Django 2.2.5 on 2019-10-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0005_auto_20191004_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enabled',
            field=models.BooleanField(default=True, help_text="If It's disabled, Subscription will be ignored"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trigger',
            field=models.ForeignKey(help_text='A Trigger that is related to this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='django_signal_notifier.Trigger'),
        ),
    ]
