# Generated by Django 2.2.3 on 2019-08-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0006_auto_20190801_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trigger',
            field=models.ForeignKey(help_text='Trigger that is related to this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='django_signal_notifier.Trigger'),
        ),
    ]
