# Generated by Django 2.2.3 on 2019-08-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0008_auto_20190801_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='This is text message from django-signal-notifier.')),
                ('context', models.CharField(default='{}', max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(choices=[('SimplePrintMessenger1', 'SimplePrintMessenger1'), ('SMTPEmailMessenger', 'SMTPEmailMessenger'), ('TelegramBotMessenger', 'TelegramBotMessenger')], default='BaseMessanger', max_length=128),
        ),
        migrations.AddField(
            model_name='backend',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_signal_notifier.Template'),
        ),
    ]
