# Generated by Django 2.2.3 on 2019-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0009_auto_20190802_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='context',
            new_name='context_str',
        ),
        migrations.RemoveField(
            model_name='template',
            name='text',
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='django_singal_notifier/templates/base.html', max_length=255),
        ),
    ]
