# Generated by Django 2.2.3 on 2019-08-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0009_auto_20190802_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(choices=[('SimplePrintMessenger1', 'SimplePrintMessenger1'), ('SMTPEmailMessenger', 'SMTPEmailMessenger'), ('TelegramBotMessenger', 'TelegramBotMessenger')], default='BaseMessanger', max_length=128),
        ),
    ]
