# Generated by Django 2.2.3 on 2019-08-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0011_auto_20190804_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='file_name',
        ),
    ]
