# Generated by Django 2.2.3 on 2019-08-08 22:45

from django.db import migrations


class Migration(migrations.Migration):
	atomic = False

	dependencies = [
		('django_signal_notifier', '0014_auto_20190808_2235'),
	]

	operations = [
		migrations.RenameModel(
			old_name='Template',
			new_name='MessageTemplate',
		),
	]
