# Generated by Django 2.2.3 on 2019-08-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0016_auto_20190808_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='verb',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
