# Generated by Django 2.2.3 on 2019-08-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0019_auto_20190809_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='context_template_str',
        ),
    ]
