# Generated by Django 2.2.3 on 2019-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0021_auto_20190809_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
        migrations.AlterField(
            model_name='backend',
            name='message_template',
            field=models.CharField(choices=[('BaseMessageTemplate', 'BaseMessageTemplate'), ('SimpleEmailMessageTemplate', 'SimpleEmailMessageTemplate'), ('SimpleTelegramMessageTemplate1', 'SimpleTelegramMessageTemplate1'), ('SimpleTelegramMessageTemplate2', 'SimpleTelegramMessageTemplate2')], default='BaseMessageTemplate', max_length=128),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='backends',
            field=models.ManyToManyField(blank=True, help_text='Backend that specified for this subscription.\n Important: Make sure that this backend message_template content can be adaptable to the trigger context', to='django_signal_notifier.Backend', verbose_name='Backend'),
        ),
    ]
