# Generated by Django 2.2.3 on 2019-08-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_notifier', '0022_auto_20190809_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend',
            old_name='name',
            new_name='messenger',
        ),
    ]
